name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Add SSH key
        run: echo "${{ secrets.EC2_SSH_KEY }}" | ssh-add -

      - name: Copy files via scp
        env:
          EC2_PUB_IP: ${{ secrets.EC2_PUB_IP }}
        run: scp -o StrictHostKeyChecking=no main.py ec2-user@${{ secrets.EC2_PUB_IP }}:/data001/LearningMate-Databricks-Backend/main.py

      - name: Restart Uvicorn
        env:
          EC2_PUB_IP: ${{ secrets.EC2_PUB_IP }}
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUB_IP }} << 'EOF'
            pkill uvicorn || true
            nohup uvicorn main:app --host 0.0.0.0 --port 8000 &
          EOF
